// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621092733_AddWorkloadLogTimeStampIndexes")]
    partial class AddWorkloadLogTimeStampIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.calendar.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Domain.calendar.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("Domain.calendar.WeekDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("WeekDays");
                });

            modelBuilder.Entity("Domain.constraints.ClassroomAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("NumberLesson")
                        .HasColumnType("integer");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("ClassroomAvailabilities");
                });

            modelBuilder.Entity("Domain.constraints.TeacherAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("NumberLesson")
                        .HasColumnType("integer");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAvailabilities");
                });

            modelBuilder.Entity("Domain.constraints.equipments.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Domain.constraints.equipments.EquipmentRoom", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "ClassroomId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("EquipmentRooms");
                });

            modelBuilder.Entity("Domain.constraints.equipments.NeededEquipment", b =>
                {
                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("CurriculumId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NeededEquipments");
                });

            modelBuilder.Entity("Domain.constraints.penalty.ConstraintConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConstraintType")
                        .HasColumnType("integer");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstraintType")
                        .IsUnique();

                    b.ToTable("ConstraintConfigs");
                });

            modelBuilder.Entity("Domain.schedule.AcademicStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AcademicStreams");
                });

            modelBuilder.Entity("Domain.schedule.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StreamId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.schedule.StreamGroups", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("StreamId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("StreamGroups");
                });

            modelBuilder.Entity("Domain.schedule.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.schedule.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeekDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeekDayId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Domain.university.buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.university.buildings.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Domain.university.common.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("Domain.university.groups.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DegreeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.university.groups.Degree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeDegree")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("Domain.university.groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Domain.university.teachers.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.university.teachers.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Domain.workload.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Double")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FavoriteBuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonType")
                        .HasColumnType("integer");

                    b.Property<bool>("Parallelism")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteBuildingId");

                    b.HasIndex("StreamId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("Domain.workload.SemesterWorkload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SemesterId");

                    b.ToTable("SemesterWorkloads");
                });

            modelBuilder.Entity("Domain.workload.WeekWorkload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<Guid>("SemesterWorkloadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SemesterWorkloadId");

                    b.HasIndex("WeekId");

                    b.ToTable("WeekWorkloads");
                });

            modelBuilder.Entity("Domain.workload.logs.SemesterLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<int>("OldValue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SemesterWorkloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SemesterWorkloadId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("SemesterLogs");
                });

            modelBuilder.Entity("Domain.workload.logs.WeekLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<int>("OldValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WeekWorkloadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeStamp");

                    b.HasIndex("WeekWorkloadId");

                    b.ToTable("WeekLogs");
                });

            modelBuilder.Entity("Domain.calendar.Week", b =>
                {
                    b.HasOne("Domain.calendar.Semester", "Semester")
                        .WithMany("Weeks")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Domain.calendar.WeekDay", b =>
                {
                    b.HasOne("Domain.calendar.Week", "Week")
                        .WithMany("WeekDays")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Domain.constraints.ClassroomAvailability", b =>
                {
                    b.HasOne("Domain.university.buildings.Classroom", "Classroom")
                        .WithMany("ClassroomAvailabilities")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Domain.constraints.TeacherAvailability", b =>
                {
                    b.HasOne("Domain.university.teachers.Teacher", "Teacher")
                        .WithMany("TeacherAvailabilities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.constraints.equipments.EquipmentRoom", b =>
                {
                    b.HasOne("Domain.university.buildings.Classroom", "Classroom")
                        .WithMany("EquipmentRooms")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.constraints.equipments.Equipment", "Equipment")
                        .WithMany("EquipmentRooms")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Domain.constraints.equipments.NeededEquipment", b =>
                {
                    b.HasOne("Domain.workload.Curriculum", "Curriculum")
                        .WithMany("NeededEquipments")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.constraints.equipments.Equipment", "Equipment")
                        .WithMany("NeededEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Domain.schedule.Lesson", b =>
                {
                    b.HasOne("Domain.university.buildings.Classroom", "Classroom")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.workload.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.calendar.Semester", null)
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.schedule.AcademicStream", "Stream")
                        .WithMany("Lessons")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.schedule.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Curriculum");

                    b.Navigation("Stream");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Domain.schedule.StreamGroups", b =>
                {
                    b.HasOne("Domain.university.groups.Group", "Group")
                        .WithMany("StreamGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.schedule.AcademicStream", "Stream")
                        .WithMany("StreamGroups")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("Domain.schedule.TimeSlot", b =>
                {
                    b.HasOne("Domain.calendar.WeekDay", "WeekDay")
                        .WithMany("TimeSlots")
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekDay");
                });

            modelBuilder.Entity("Domain.university.buildings.Classroom", b =>
                {
                    b.HasOne("Domain.university.buildings.Building", "Building")
                        .WithMany("Classrooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Domain.university.groups.Course", b =>
                {
                    b.HasOne("Domain.university.groups.Degree", "Degree")
                        .WithMany("Courses")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("Domain.university.groups.Degree", b =>
                {
                    b.HasOne("Domain.university.common.Institute", "Institute")
                        .WithMany("Degrees")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Domain.university.groups.Group", b =>
                {
                    b.HasOne("Domain.university.groups.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.university.groups.Group", "ParentGroup")
                        .WithMany("Groups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Domain.university.teachers.Department", b =>
                {
                    b.HasOne("Domain.university.common.Institute", "Institute")
                        .WithMany("Departments")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Domain.university.teachers.Teacher", b =>
                {
                    b.HasOne("Domain.university.teachers.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.workload.Curriculum", b =>
                {
                    b.HasOne("Domain.university.buildings.Building", "FavoriteBuilding")
                        .WithMany("Curriculums")
                        .HasForeignKey("FavoriteBuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.schedule.AcademicStream", "Stream")
                        .WithMany("Curriculums")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.schedule.Subject", "Subject")
                        .WithMany("Curriculums")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.university.teachers.Teacher", "Teacher")
                        .WithMany("Curriculums")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteBuilding");

                    b.Navigation("Stream");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.workload.SemesterWorkload", b =>
                {
                    b.HasOne("Domain.workload.Curriculum", "Curriculum")
                        .WithMany("SemesterWorkloads")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.calendar.Semester", "Semester")
                        .WithMany("SemesterWorkloads")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Domain.workload.WeekWorkload", b =>
                {
                    b.HasOne("Domain.workload.Curriculum", "Curriculum")
                        .WithMany("WeekWorkloads")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.workload.SemesterWorkload", "SemesterWorkload")
                        .WithMany("WeekWorkloads")
                        .HasForeignKey("SemesterWorkloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.calendar.Week", "Week")
                        .WithMany("WeekWorkloads")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("SemesterWorkload");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Domain.workload.logs.SemesterLog", b =>
                {
                    b.HasOne("Domain.workload.SemesterWorkload", "SemesterWorkload")
                        .WithMany("SemesterLogs")
                        .HasForeignKey("SemesterWorkloadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SemesterWorkload");
                });

            modelBuilder.Entity("Domain.workload.logs.WeekLog", b =>
                {
                    b.HasOne("Domain.workload.WeekWorkload", "WeekWorkload")
                        .WithMany("WeekLogs")
                        .HasForeignKey("WeekWorkloadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WeekWorkload");
                });

            modelBuilder.Entity("Domain.calendar.Semester", b =>
                {
                    b.Navigation("SemesterWorkloads");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Domain.calendar.Week", b =>
                {
                    b.Navigation("WeekDays");

                    b.Navigation("WeekWorkloads");
                });

            modelBuilder.Entity("Domain.calendar.WeekDay", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Domain.constraints.equipments.Equipment", b =>
                {
                    b.Navigation("EquipmentRooms");

                    b.Navigation("NeededEquipments");
                });

            modelBuilder.Entity("Domain.schedule.AcademicStream", b =>
                {
                    b.Navigation("Curriculums");

                    b.Navigation("Lessons");

                    b.Navigation("StreamGroups");
                });

            modelBuilder.Entity("Domain.schedule.Subject", b =>
                {
                    b.Navigation("Curriculums");
                });

            modelBuilder.Entity("Domain.university.buildings.Building", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Curriculums");
                });

            modelBuilder.Entity("Domain.university.buildings.Classroom", b =>
                {
                    b.Navigation("ClassroomAvailabilities");

                    b.Navigation("EquipmentRooms");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.university.common.Institute", b =>
                {
                    b.Navigation("Degrees");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Domain.university.groups.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Domain.university.groups.Degree", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Domain.university.groups.Group", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("StreamGroups");
                });

            modelBuilder.Entity("Domain.university.teachers.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.university.teachers.Teacher", b =>
                {
                    b.Navigation("Curriculums");

                    b.Navigation("TeacherAvailabilities");
                });

            modelBuilder.Entity("Domain.workload.Curriculum", b =>
                {
                    b.Navigation("NeededEquipments");

                    b.Navigation("SemesterWorkloads");

                    b.Navigation("WeekWorkloads");
                });

            modelBuilder.Entity("Domain.workload.SemesterWorkload", b =>
                {
                    b.Navigation("SemesterLogs");

                    b.Navigation("WeekWorkloads");
                });

            modelBuilder.Entity("Domain.workload.WeekWorkload", b =>
                {
                    b.Navigation("WeekLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
